spring:
  datasource:
    name: lorite
    generate-unique-name: false
  h2:
    console:
      enabled: true
  codec:
      max-in-memory-size: 50MB
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 50
